export type DefaultMenuItem = {
  category: string;
  name: string;
  price: number;
  sort_order: number;
};

export const DEFAULT_MENU: DefaultMenuItem[] = [
  { category: 'Porcoes', name: 'Isca de Peixe - Inteira', price: 150, sort_order: 10 },
  { category: 'Porcoes', name: 'Isca de Peixe - Meia', price: 120, sort_order: 20 },
  { category: 'Porcoes', name: 'Isca de Cacao - Inteira', price: 150, sort_order: 30 },
  { category: 'Porcoes', name: 'Isca de Cacao - Meia', price: 120, sort_order: 40 },
  { category: 'Porcoes', name: 'Porquinho - Inteira', price: 150, sort_order: 50 },
  { category: 'Porcoes', name: 'Porquinho - Meia', price: 120, sort_order: 60 },
  { category: 'Porcoes', name: 'Sardinha', price: 150, sort_order: 70 },
  { category: 'Porcoes', name: 'Manjubinha', price: 150, sort_order: 80 },
  { category: 'Porcoes', name: 'Camarao - Inteira', price: 150, sort_order: 90 },
  { category: 'Porcoes', name: 'Camarao - Meia', price: 120, sort_order: 100 },
  { category: 'Porcoes', name: 'Camarao Paulista', price: 160, sort_order: 110 },
  { category: 'Porcoes', name: 'Lula a Dore - Inteira', price: 170, sort_order: 120 },
  { category: 'Porcoes', name: 'Lula a Dore - Meia', price: 140, sort_order: 130 },
  { category: 'Porcoes', name: 'Frango a Passarinho', price: 120, sort_order: 140 },
  { category: 'Porcoes', name: 'File de Frango Acebolado', price: 120, sort_order: 150 },
  { category: 'Porcoes', name: 'File de Frango c/ Fritas', price: 120, sort_order: 160 },
  { category: 'Porcoes', name: 'Calabresa Acebolada', price: 120, sort_order: 170 },
  { category: 'Porcoes', name: 'Batata Frita - Inteira', price: 80, sort_order: 180 },
  { category: 'Porcoes', name: 'Batata Frita - Meia', price: 50, sort_order: 190 },
  { category: 'Porcoes', name: 'Batata Maluca com Bacon e Cheddar', price: 100, sort_order: 200 },
  { category: 'Porcoes', name: 'Cebola Empanada', price: 50, sort_order: 210 },
  { category: 'Porcoes', name: 'Contra File c/ Fritas', price: 200, sort_order: 220 },
  { category: 'Porcoes', name: 'Mega 2 Peixes com Fritas e Cebola', price: 250, sort_order: 230 },
  { category: 'Porcoes', name: 'Mega 4 Peixes com Fritas e Cebola', price: 400, sort_order: 240 },
  { category: 'Adicionais', name: 'Acrescimo de Fritas', price: 10, sort_order: 250 },
  { category: 'Pasteis', name: 'Pastel de Carne', price: 15, sort_order: 260 },
  { category: 'Pasteis', name: 'Pastel de Carne c/ Queijo ou Catupiry', price: 18, sort_order: 270 },
  { category: 'Pasteis', name: 'Pastel de Carne c/ Ovo', price: 18, sort_order: 280 },
  { category: 'Pasteis', name: 'Pastel de Queijo', price: 15, sort_order: 290 },
  { category: 'Pasteis', name: 'Pastel de Pizza', price: 15, sort_order: 300 },
  { category: 'Pasteis', name: 'Pastel de Frango', price: 15, sort_order: 310 },
  { category: 'Pasteis', name: 'Pastel de Frango c/ Queijo ou Catupiry', price: 18, sort_order: 320 },
  { category: 'Pasteis', name: 'Pastel de Calabresa', price: 15, sort_order: 330 },
  { category: 'Pasteis', name: 'Pastel de Calabresa c/ Queijo ou Catupiry', price: 18, sort_order: 340 },
  { category: 'Pasteis', name: 'Pastel de Camarao', price: 25, sort_order: 350 },
  { category: 'Pasteis', name: 'Pastel de Carne Seca', price: 25, sort_order: 360 },
  { category: 'Pasteis', name: 'Pastel de Nutella', price: 22, sort_order: 370 },
  { category: 'Pasteis', name: 'Pastel de Nutella c/ Morango', price: 25, sort_order: 380 },
  { category: 'Porcao de Pasteizinhos', name: 'Pasteizinhos 24 unidades', price: 100, sort_order: 390 },
  { category: 'Porcao de Pasteizinhos', name: 'Pasteizinhos 18 unidades', price: 70, sort_order: 400 },
  { category: 'Batidas e Caipirinhas', name: 'Vodka Absolut', price: 50, sort_order: 410 },
  { category: 'Batidas e Caipirinhas', name: 'Vodka Smirnoff', price: 35, sort_order: 420 },
  { category: 'Batidas e Caipirinhas', name: 'Saque', price: 35, sort_order: 430 },
  { category: 'Batidas e Caipirinhas', name: 'Pinga', price: 25, sort_order: 440 },
  { category: 'Batidas e Caipirinhas', name: 'Pina Colada', price: 40, sort_order: 450 },
  { category: 'Batidas e Caipirinhas', name: 'Espanhola', price: 25, sort_order: 460 },
  { category: 'Batidas e Caipirinhas', name: 'Tropical com 2 frutas - acrescimo', price: 5, sort_order: 470 },
  { category: 'Bebidas', name: 'Refrigerante Lata', price: 8, sort_order: 480 },
  { category: 'Bebidas', name: 'Skol', price: 8, sort_order: 490 },
  { category: 'Bebidas', name: 'Brahma', price: 8, sort_order: 500 },
  { category: 'Bebidas', name: 'Itaipava', price: 8, sort_order: 510 },
  { category: 'Bebidas', name: 'Heineken', price: 12, sort_order: 520 },
  { category: 'Bebidas', name: 'Budweiser', price: 12, sort_order: 530 },
  { category: 'Bebidas', name: 'Duplo Malte', price: 12, sort_order: 540 },
  { category: 'Bebidas', name: 'Original', price: 12, sort_order: 550 },
  { category: 'Bebidas', name: 'Cerveja sem Alcool', price: 12, sort_order: 560 },
  { category: 'Bebidas', name: 'Energetico', price: 20, sort_order: 570 },
  { category: 'Bebidas', name: 'Agua', price: 5, sort_order: 580 },
  { category: 'Bebidas', name: 'Agua c/ Gas', price: 8, sort_order: 590 },
  { category: 'Bebidas', name: 'H2OH', price: 10, sort_order: 600 },
  { category: 'Doses', name: 'Campari', price: 20, sort_order: 610 },
  { category: 'Doses', name: 'Whisky Red', price: 30, sort_order: 620 },
  { category: 'Doses', name: 'Smirnoff', price: 15, sort_order: 630 },
  { category: 'Doses', name: '51 ou Velho Barreiro', price: 5, sort_order: 640 },
  { category: 'Doses', name: 'Gin com Tonica', price: 35, sort_order: 650 },
  { category: 'Sucos', name: 'Suco de Abacaxi', price: 20, sort_order: 660 },
  { category: 'Sucos', name: 'Suco de Caju', price: 20, sort_order: 670 },
  { category: 'Sucos', name: 'Suco de Coco', price: 20, sort_order: 680 },
  { category: 'Sucos', name: 'Suco de Kiwi', price: 20, sort_order: 690 },
  { category: 'Sucos', name: 'Suco de Laranja', price: 20, sort_order: 700 },
  { category: 'Sucos', name: 'Suco de Limao', price: 20, sort_order: 710 },
  { category: 'Sucos', name: 'Suco de Manga', price: 20, sort_order: 720 },
  { category: 'Sucos', name: 'Suco de Maracuja', price: 20, sort_order: 730 },
];
